### ISSUE TITLE
typhoeus dependancy outdated

### ISSUE THREAD

**Issue by justinlyman** [MyPureCloud/platform-client-sdk-ruby#2]
The typhoeus dependency needs to be updated to >= v1.0 . You are currently using 0.2 which is extremely outdated, and we are unable to use this SDK as we have other gems that depend on the newer version of typhoeus.

**Comment by timsmithgenesys** [comment]
This SDK has reached end of life and is no longer being maintained. https://developer.mypurecloud.com/forum/t/announcement-genesys-cloud-ruby-sdk-end-of-life/8850/4
